apiVersion: v1
kind: Secret
metadata:
  name: ghcr-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson | b64enc | quote }} 